sonar.projectKey=taller-sast-monorepo
sonar.projectName=Taller SAST Monorepo
sonar.projectVersion=1.0

# Path to source directories (relativo a la raíz)
sonar.sources=apps

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclusión de archivos y directorios no deseados para el análisis
sonar.exclusions=**/node_modules/**, **/dist/**, **/build/**, **/*.spec.js, **/*.test.js, **/coverage/**
